# serverless.yml

service: express-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY